### PR TITLE
Remove thumbnails

### PR DESCRIPTION
**Pull request by DonRichards**
Not sure what changed. Using this PR to see in a clean way

### CODE REVIEW

**Comment by DonRichards** [comment]
Noting this is still pointing to https://www.lib.utk.edu/template/ for some resources and needs to be changed to a local URL. If for some reason this resource changes, this could cause massive problems.

**Comment by DonRichards** [comment]
We are using CAS so I don't know why page--user--login.tpl.php & page--user--password.tpl.php are included. This will only show on a developer machines. page--user--register.tpl.php & page--user--reset.tpl.php have no practical applications for our development environment and will never be used in production because of our implementation of UTK's CAS single sign on system.

**Comment by CanOfBees** [comment]
Self-assigning for review

**Comment by DonRichards** [comment]
Thanks @CanOfBees

**Review by CanOfBees — APPROVED** [review]
@DonRichards as far as I can tell, this PR looks fine. The submission->accept->publish workflow does not seem to be impacted at all. Solr searches are correct in that they do not display thumbnails, and Browsing does not display thumbnails either.

The only missing piece is having Browse default to List view, but I'm not sure if that was originally part of this work, or if it fits in to another task.

Thanks,
Bridger

**Comment by CanOfBees** [comment]
@DonRichards a comment re the slow initial page load: it only seems to happen with Chromium and the timed result was ~16 seconds to load on PR-6. On the horizontal branch, I'm getting page timeouts on initial load, but then quick load times after the initial failed load.

Let me know and I can try to provide additional details.
Edit: checked the /var/log/apache2/ logs and there aren't any explicit errors/access problems being thrown by the slow connection, afaict, but will recheck if you want more information.

**Comment by DonRichards** [comment]
Embarrassingly the magnitude of files that had changed was my fault. I had inadvertently attempted to merge into '**master**' instead of '**horizon**'.

**Review by cdeaneGit — APPROVED** [review]
1. Perform vagrant up on Trace (master)
2. Do standard test on submit, accept, publish of an ETD.
3. Review Results for Browse and Test.
4. Follow directions on trace wiki for Testing a Pull Request. (https://github.com/utkdigitalinitiatives/TRACE/wiki/Pull-Request)
5. Change UTKdrupal to branch pr-6.
6. Do standard test on submit, accept, publish of an ETD.
7.  Review Results for Browse and Test.
The thumbnails have been removed.

This task has been completed. 
I approve merging this change.

**Pull request merged**
